/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegratorApi);
  }
}(this, function(expect, IntegratorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IntegratorApi.Application();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Application', function() {
    it('should create an instance of Application', function() {
      // uncomment below and update the code to test Application
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be.a(IntegratorApi.Application);
    });

    it('should have the property hostId (base name: "hostId")', function() {
      // uncomment below and update the code to test the property hostId
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property applicationId (base name: "applicationId")', function() {
      // uncomment below and update the code to test the property applicationId
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property applicationName (base name: "applicationName")', function() {
      // uncomment below and update the code to test the property applicationName
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property portRunning (base name: "portRunning")', function() {
      // uncomment below and update the code to test the property portRunning
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property loginPageURL (base name: "loginPageURL")', function() {
      // uncomment below and update the code to test the property loginPageURL
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property homePageURL (base name: "homePageURL")', function() {
      // uncomment below and update the code to test the property homePageURL
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property monitoringFingerprint (base name: "monitoringFingerprint")', function() {
      // uncomment below and update the code to test the property monitoringFingerprint
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property reserved1 (base name: "reserved1")', function() {
      // uncomment below and update the code to test the property reserved1
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property reserved2 (base name: "reserved2")', function() {
      // uncomment below and update the code to test the property reserved2
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

    it('should have the property reserved3 (base name: "reserved3")', function() {
      // uncomment below and update the code to test the property reserved3
      //var instane = new IntegratorApi.Application();
      //expect(instance).to.be();
    });

  });

}));
