/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegratorApi);
  }
}(this, function(expect, IntegratorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IntegratorApi.Metadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Metadata', function() {
    it('should create an instance of Metadata', function() {
      // uncomment below and update the code to test Metadata
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be.a(IntegratorApi.Metadata);
    });

    it('should have the property metadataId (base name: "metadataId")', function() {
      // uncomment below and update the code to test the property metadataId
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property host (base name: "host")', function() {
      // uncomment below and update the code to test the property host
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property lastRenewal (base name: "lastRenewal")', function() {
      // uncomment below and update the code to test the property lastRenewal
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property complexity (base name: "complexity")', function() {
      // uncomment below and update the code to test the property complexity
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property generatedBefore (base name: "generatedBefore")', function() {
      // uncomment below and update the code to test the property generatedBefore
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "groupId")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new IntegratorApi.Metadata();
      //expect(instance).to.be();
    });

  });

}));
