/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.IntegratorApi);
  }
}(this, function(expect, IntegratorApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new IntegratorApi.PostAdminSysteminformationResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostAdminSysteminformationResponse', function() {
    it('should create an instance of PostAdminSysteminformationResponse', function() {
      // uncomment below and update the code to test PostAdminSysteminformationResponse
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be.a(IntegratorApi.PostAdminSysteminformationResponse);
    });

    it('should have the property operatingSystem (base name: "operatingSystem")', function() {
      // uncomment below and update the code to test the property operatingSystem
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property processorInformation (base name: "processorInformation")', function() {
      // uncomment below and update the code to test the property processorInformation
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property timeOnSystem (base name: "timeOnSystem")', function() {
      // uncomment below and update the code to test the property timeOnSystem
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property systemUptime (base name: "systemUptime")', function() {
      // uncomment below and update the code to test the property systemUptime
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property forgivaVersion (base name: "forgivaVersion")', function() {
      // uncomment below and update the code to test the property forgivaVersion
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property hostname (base name: "hostname")', function() {
      // uncomment below and update the code to test the property hostname
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property ipConfiguration (base name: "ipConfiguration")', function() {
      // uncomment below and update the code to test the property ipConfiguration
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property javaEnvironment (base name: "javaEnvironment")', function() {
      // uncomment below and update the code to test the property javaEnvironment
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

    it('should have the property enabledFeatures (base name: "enabledFeatures")', function() {
      // uncomment below and update the code to test the property enabledFeatures
      //var instane = new IntegratorApi.PostAdminSysteminformationResponse();
      //expect(instance).to.be();
    });

  });

}));
