/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Report from './Report';

/**
 * The PostAdminReportsResponse model module.
 * @module model/PostAdminReportsResponse
 * @version 1.0
 */
class PostAdminReportsResponse {
    /**
     * Constructs a new <code>PostAdminReportsResponse</code>.
     * @alias module:model/PostAdminReportsResponse
     */
    constructor() { 
        
        PostAdminReportsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminReportsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminReportsResponse} obj Optional instance to populate.
     * @return {module:model/PostAdminReportsResponse} The populated <code>PostAdminReportsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminReportsResponse();

            if (data.hasOwnProperty('reports')) {
                obj['reports'] = ApiClient.convertToType(data['reports'], [Report]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Report>} reports
 */
PostAdminReportsResponse.prototype['reports'] = undefined;






export default PostAdminReportsResponse;

