/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Metadata from './Metadata';

/**
 * The PostUserMetadataBygroupResponse model module.
 * @module model/PostUserMetadataBygroupResponse
 * @version 1.0
 */
class PostUserMetadataBygroupResponse {
    /**
     * Constructs a new <code>PostUserMetadataBygroupResponse</code>.
     * @alias module:model/PostUserMetadataBygroupResponse
     */
    constructor() { 
        
        PostUserMetadataBygroupResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUserMetadataBygroupResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserMetadataBygroupResponse} obj Optional instance to populate.
     * @return {module:model/PostUserMetadataBygroupResponse} The populated <code>PostUserMetadataBygroupResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserMetadataBygroupResponse();

            if (data.hasOwnProperty('metadatas')) {
                obj['metadatas'] = ApiClient.convertToType(data['metadatas'], [Metadata]);
            }
            if (data.hasOwnProperty('totalRecords')) {
                obj['totalRecords'] = ApiClient.convertToType(data['totalRecords'], 'Number');
            }
            if (data.hasOwnProperty('startIdx')) {
                obj['startIdx'] = ApiClient.convertToType(data['startIdx'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Metadata>} metadatas
 */
PostUserMetadataBygroupResponse.prototype['metadatas'] = undefined;

/**
 * Total number of records of metadata within the group.
 * @member {Number} totalRecords
 */
PostUserMetadataBygroupResponse.prototype['totalRecords'] = undefined;

/**
 * Start index of the records returned.
 * @member {Number} startIdx
 */
PostUserMetadataBygroupResponse.prototype['startIdx'] = undefined;






export default PostUserMetadataBygroupResponse;

