/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostUserMetadataGroupRemoveRequest model module.
 * @module model/PostUserMetadataGroupRemoveRequest
 * @version 1.0
 */
class PostUserMetadataGroupRemoveRequest {
    /**
     * Constructs a new <code>PostUserMetadataGroupRemoveRequest</code>.
     * @alias module:model/PostUserMetadataGroupRemoveRequest
     * @param metadataGroupId {String} 
     */
    constructor(metadataGroupId) { 
        
        PostUserMetadataGroupRemoveRequest.initialize(this, metadataGroupId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metadataGroupId) { 
        obj['metadataGroupId'] = metadataGroupId;
    }

    /**
     * Constructs a <code>PostUserMetadataGroupRemoveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserMetadataGroupRemoveRequest} obj Optional instance to populate.
     * @return {module:model/PostUserMetadataGroupRemoveRequest} The populated <code>PostUserMetadataGroupRemoveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserMetadataGroupRemoveRequest();

            if (data.hasOwnProperty('metadataGroupId')) {
                obj['metadataGroupId'] = ApiClient.convertToType(data['metadataGroupId'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} metadataGroupId
 */
PostUserMetadataGroupRemoveRequest.prototype['metadataGroupId'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostUserMetadataGroupRemoveRequest.prototype['header'] = undefined;






export default PostUserMetadataGroupRemoveRequest;

