/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostLoginRequest model module.
 * @module model/PostLoginRequest
 * @version 1.0
 */
class PostLoginRequest {
    /**
     * Constructs a new <code>PostLoginRequest</code>.
     * @alias module:model/PostLoginRequest
     */
    constructor() { 
        
        PostLoginRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostLoginRequest} obj Optional instance to populate.
     * @return {module:model/PostLoginRequest} The populated <code>PostLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostLoginRequest();

            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('loginOverLdap')) {
                obj['loginOverLdap'] = ApiClient.convertToType(data['loginOverLdap'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Header} header
 */
PostLoginRequest.prototype['header'] = undefined;

/**
 * User name encrypted with session public key
 * @member {String} username
 */
PostLoginRequest.prototype['username'] = undefined;

/**
 * Hash of password encrypted with session public key.
 * @member {String} password
 */
PostLoginRequest.prototype['password'] = undefined;

/**
 * Requests login over LDAP servers
 * @member {Boolean} loginOverLdap
 */
PostLoginRequest.prototype['loginOverLdap'] = undefined;






export default PostLoginRequest;

