/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostUserBackupImportRequest model module.
 * @module model/PostUserBackupImportRequest
 * @version 1.0
 */
class PostUserBackupImportRequest {
    /**
     * Constructs a new <code>PostUserBackupImportRequest</code>.
     * @alias module:model/PostUserBackupImportRequest
     */
    constructor() { 
        
        PostUserBackupImportRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUserBackupImportRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserBackupImportRequest} obj Optional instance to populate.
     * @return {module:model/PostUserBackupImportRequest} The populated <code>PostUserBackupImportRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserBackupImportRequest();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * Exported data from /user/backup/export service
 * @member {String} data
 */
PostUserBackupImportRequest.prototype['data'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostUserBackupImportRequest.prototype['header'] = undefined;






export default PostUserBackupImportRequest;

