/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Application from './Application';

/**
 * The PostAdminApplicationsResponse model module.
 * @module model/PostAdminApplicationsResponse
 * @version 1.0
 */
class PostAdminApplicationsResponse {
    /**
     * Constructs a new <code>PostAdminApplicationsResponse</code>.
     * @alias module:model/PostAdminApplicationsResponse
     */
    constructor() { 
        
        PostAdminApplicationsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminApplicationsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminApplicationsResponse} obj Optional instance to populate.
     * @return {module:model/PostAdminApplicationsResponse} The populated <code>PostAdminApplicationsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminApplicationsResponse();

            if (data.hasOwnProperty('applications')) {
                obj['applications'] = ApiClient.convertToType(data['applications'], [Application]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Application>} applications
 */
PostAdminApplicationsResponse.prototype['applications'] = undefined;






export default PostAdminApplicationsResponse;

