/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Application from './Application';
import Header from './Header';

/**
 * The PostAdminApplicationUpdateRequest model module.
 * @module model/PostAdminApplicationUpdateRequest
 * @version 1.0
 */
class PostAdminApplicationUpdateRequest {
    /**
     * Constructs a new <code>PostAdminApplicationUpdateRequest</code>.
     * @alias module:model/PostAdminApplicationUpdateRequest
     */
    constructor() { 
        
        PostAdminApplicationUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminApplicationUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminApplicationUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminApplicationUpdateRequest} The populated <code>PostAdminApplicationUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminApplicationUpdateRequest();

            if (data.hasOwnProperty('application')) {
                obj['application'] = Application.constructFromObject(data['application']);
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Application} application
 */
PostAdminApplicationUpdateRequest.prototype['application'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostAdminApplicationUpdateRequest.prototype['header'] = undefined;






export default PostAdminApplicationUpdateRequest;

