/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostLogin2faRequest model module.
 * @module model/PostLogin2faRequest
 * @version 1.0
 */
class PostLogin2faRequest {
    /**
     * Constructs a new <code>PostLogin2faRequest</code>.
     * @alias module:model/PostLogin2faRequest
     */
    constructor() { 
        
        PostLogin2faRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostLogin2faRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostLogin2faRequest} obj Optional instance to populate.
     * @return {module:model/PostLogin2faRequest} The populated <code>PostLogin2faRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostLogin2faRequest();

            if (data.hasOwnProperty('twoFACode')) {
                obj['twoFACode'] = ApiClient.convertToType(data['twoFACode'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * 2FA code hashed with specified hash algorithm in /session service.
 * @member {String} twoFACode
 */
PostLogin2faRequest.prototype['twoFACode'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostLogin2faRequest.prototype['header'] = undefined;






export default PostLogin2faRequest;

