/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostAdminResourceusageResponseCpuUsageByDay from './PostAdminResourceusageResponseCpuUsageByDay';
import PostAdminResourceusageResponseCpuUsageByHour from './PostAdminResourceusageResponseCpuUsageByHour';

/**
 * The PostAdminResourceusageResponse model module.
 * @module model/PostAdminResourceusageResponse
 * @version 1.0
 */
class PostAdminResourceusageResponse {
    /**
     * Constructs a new <code>PostAdminResourceusageResponse</code>.
     * @alias module:model/PostAdminResourceusageResponse
     */
    constructor() { 
        
        PostAdminResourceusageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminResourceusageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminResourceusageResponse} obj Optional instance to populate.
     * @return {module:model/PostAdminResourceusageResponse} The populated <code>PostAdminResourceusageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminResourceusageResponse();

            if (data.hasOwnProperty('cpuUsagePercentage')) {
                obj['cpuUsagePercentage'] = ApiClient.convertToType(data['cpuUsagePercentage'], 'String');
            }
            if (data.hasOwnProperty('totalMemory')) {
                obj['totalMemory'] = ApiClient.convertToType(data['totalMemory'], 'String');
            }
            if (data.hasOwnProperty('usedMemory')) {
                obj['usedMemory'] = ApiClient.convertToType(data['usedMemory'], 'String');
            }
            if (data.hasOwnProperty('totalDiskspace')) {
                obj['totalDiskspace'] = ApiClient.convertToType(data['totalDiskspace'], 'String');
            }
            if (data.hasOwnProperty('usedDiskspace')) {
                obj['usedDiskspace'] = ApiClient.convertToType(data['usedDiskspace'], 'String');
            }
            if (data.hasOwnProperty('cpuUsageByHour')) {
                obj['cpuUsageByHour'] = ApiClient.convertToType(data['cpuUsageByHour'], [PostAdminResourceusageResponseCpuUsageByHour]);
            }
            if (data.hasOwnProperty('cpuUsageByDay')) {
                obj['cpuUsageByDay'] = ApiClient.convertToType(data['cpuUsageByDay'], [PostAdminResourceusageResponseCpuUsageByDay]);
            }
            if (data.hasOwnProperty('totalUsers')) {
                obj['totalUsers'] = ApiClient.convertToType(data['totalUsers'], 'String');
            }
            if (data.hasOwnProperty('totalUniqueHosts')) {
                obj['totalUniqueHosts'] = ApiClient.convertToType(data['totalUniqueHosts'], 'String');
            }
            if (data.hasOwnProperty('databaseSize')) {
                obj['databaseSize'] = ApiClient.convertToType(data['databaseSize'], 'String');
            }
            if (data.hasOwnProperty('averagePasswordGenerationTime')) {
                obj['averagePasswordGenerationTime'] = ApiClient.convertToType(data['averagePasswordGenerationTime'], 'String');
            }
            if (data.hasOwnProperty('serverPingTime')) {
                obj['serverPingTime'] = ApiClient.convertToType(data['serverPingTime'], 'String');
            }
            if (data.hasOwnProperty('averageDatabaseResponseTime')) {
                obj['averageDatabaseResponseTime'] = ApiClient.convertToType(data['averageDatabaseResponseTime'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cpuUsagePercentage
 */
PostAdminResourceusageResponse.prototype['cpuUsagePercentage'] = undefined;

/**
 * Total memory in MB.
 * @member {String} totalMemory
 */
PostAdminResourceusageResponse.prototype['totalMemory'] = undefined;

/**
 * Used memory in MB.
 * @member {String} usedMemory
 */
PostAdminResourceusageResponse.prototype['usedMemory'] = undefined;

/**
 * Total disk space in MB.
 * @member {String} totalDiskspace
 */
PostAdminResourceusageResponse.prototype['totalDiskspace'] = undefined;

/**
 * Used disk space in MB.
 * @member {String} usedDiskspace
 */
PostAdminResourceusageResponse.prototype['usedDiskspace'] = undefined;

/**
 * @member {Array.<module:model/PostAdminResourceusageResponseCpuUsageByHour>} cpuUsageByHour
 */
PostAdminResourceusageResponse.prototype['cpuUsageByHour'] = undefined;

/**
 * @member {Array.<module:model/PostAdminResourceusageResponseCpuUsageByDay>} cpuUsageByDay
 */
PostAdminResourceusageResponse.prototype['cpuUsageByDay'] = undefined;

/**
 * Total users of Forgiva Enterprise including LDAP users.
 * @member {String} totalUsers
 */
PostAdminResourceusageResponse.prototype['totalUsers'] = undefined;

/**
 * Total unique host count recorded in the database.
 * @member {String} totalUniqueHosts
 */
PostAdminResourceusageResponse.prototype['totalUniqueHosts'] = undefined;

/**
 * Total database size in MB.
 * @member {String} databaseSize
 */
PostAdminResourceusageResponse.prototype['databaseSize'] = undefined;

/**
 * Average password generation time in seconds.
 * @member {String} averagePasswordGenerationTime
 */
PostAdminResourceusageResponse.prototype['averagePasswordGenerationTime'] = undefined;

/**
 * Forgiva Server ping time in MS.
 * @member {String} serverPingTime
 */
PostAdminResourceusageResponse.prototype['serverPingTime'] = undefined;

/**
 * If database is on remote average response time in MS.
 * @member {String} averageDatabaseResponseTime
 */
PostAdminResourceusageResponse.prototype['averageDatabaseResponseTime'] = undefined;






export default PostAdminResourceusageResponse;

