/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';
import User from './User';

/**
 * The PostAdminUserUpdateRequest model module.
 * @module model/PostAdminUserUpdateRequest
 * @version 1.0
 */
class PostAdminUserUpdateRequest {
    /**
     * Constructs a new <code>PostAdminUserUpdateRequest</code>.
     * @alias module:model/PostAdminUserUpdateRequest
     * @param user {module:model/User} 
     */
    constructor(user) { 
        
        PostAdminUserUpdateRequest.initialize(this, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, user) { 
        obj['user'] = user;
    }

    /**
     * Constructs a <code>PostAdminUserUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminUserUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminUserUpdateRequest} The populated <code>PostAdminUserUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminUserUpdateRequest();

            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Header} header
 */
PostAdminUserUpdateRequest.prototype['header'] = undefined;

/**
 * @member {module:model/User} user
 */
PostAdminUserUpdateRequest.prototype['user'] = undefined;






export default PostAdminUserUpdateRequest;

