/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostUser2faEnableRequest model module.
 * @module model/PostUser2faEnableRequest
 * @version 1.0
 */
class PostUser2faEnableRequest {
    /**
     * Constructs a new <code>PostUser2faEnableRequest</code>.
     * @alias module:model/PostUser2faEnableRequest
     */
    constructor() { 
        
        PostUser2faEnableRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUser2faEnableRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUser2faEnableRequest} obj Optional instance to populate.
     * @return {module:model/PostUser2faEnableRequest} The populated <code>PostUser2faEnableRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUser2faEnableRequest();

            if (data.hasOwnProperty('sotpCode')) {
                obj['sotpCode'] = ApiClient.convertToType(data['sotpCode'], 'String');
            }
            if (data.hasOwnProperty('validationCode')) {
                obj['validationCode'] = ApiClient.convertToType(data['validationCode'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} sotpCode
 */
PostUser2faEnableRequest.prototype['sotpCode'] = undefined;

/**
 * @member {String} validationCode
 */
PostUser2faEnableRequest.prototype['validationCode'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostUser2faEnableRequest.prototype['header'] = undefined;






export default PostUser2faEnableRequest;

