/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostAdminUsergroupRemoveRequest model module.
 * @module model/PostAdminUsergroupRemoveRequest
 * @version 1.0
 */
class PostAdminUsergroupRemoveRequest {
    /**
     * Constructs a new <code>PostAdminUsergroupRemoveRequest</code>.
     * @alias module:model/PostAdminUsergroupRemoveRequest
     * @param userGroupId {String} 
     */
    constructor(userGroupId) { 
        
        PostAdminUsergroupRemoveRequest.initialize(this, userGroupId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userGroupId) { 
        obj['userGroupId'] = userGroupId;
    }

    /**
     * Constructs a <code>PostAdminUsergroupRemoveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminUsergroupRemoveRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminUsergroupRemoveRequest} The populated <code>PostAdminUsergroupRemoveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminUsergroupRemoveRequest();

            if (data.hasOwnProperty('userGroupId')) {
                obj['userGroupId'] = ApiClient.convertToType(data['userGroupId'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} userGroupId
 */
PostAdminUsergroupRemoveRequest.prototype['userGroupId'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostAdminUsergroupRemoveRequest.prototype['header'] = undefined;






export default PostAdminUsergroupRemoveRequest;

