/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Application from './Application';
import Header from './Header';

/**
 * The PostAdminApplicationAddRequest model module.
 * @module model/PostAdminApplicationAddRequest
 * @version 1.0
 */
class PostAdminApplicationAddRequest {
    /**
     * Constructs a new <code>PostAdminApplicationAddRequest</code>.
     * @alias module:model/PostAdminApplicationAddRequest
     * @param application {module:model/Application} 
     */
    constructor(application) { 
        
        PostAdminApplicationAddRequest.initialize(this, application);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, application) { 
        obj['application'] = application;
    }

    /**
     * Constructs a <code>PostAdminApplicationAddRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminApplicationAddRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminApplicationAddRequest} The populated <code>PostAdminApplicationAddRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminApplicationAddRequest();

            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('application')) {
                obj['application'] = Application.constructFromObject(data['application']);
            }
            if (data.hasOwnProperty('hostId')) {
                obj['hostId'] = ApiClient.convertToType(data['hostId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Header} header
 */
PostAdminApplicationAddRequest.prototype['header'] = undefined;

/**
 * @member {module:model/Application} application
 */
PostAdminApplicationAddRequest.prototype['application'] = undefined;

/**
 * Host id to add into.
 * @member {Number} hostId
 */
PostAdminApplicationAddRequest.prototype['hostId'] = undefined;






export default PostAdminApplicationAddRequest;

