/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Host from './Host';

/**
 * The PostAdminHostsResponse model module.
 * @module model/PostAdminHostsResponse
 * @version 1.0
 */
class PostAdminHostsResponse {
    /**
     * Constructs a new <code>PostAdminHostsResponse</code>.
     * @alias module:model/PostAdminHostsResponse
     */
    constructor() { 
        
        PostAdminHostsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminHostsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminHostsResponse} obj Optional instance to populate.
     * @return {module:model/PostAdminHostsResponse} The populated <code>PostAdminHostsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminHostsResponse();

            if (data.hasOwnProperty('hosts')) {
                obj['hosts'] = ApiClient.convertToType(data['hosts'], [Host]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Host>} hosts
 */
PostAdminHostsResponse.prototype['hosts'] = undefined;






export default PostAdminHostsResponse;

