/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostAdminHostRemoveRequest model module.
 * @module model/PostAdminHostRemoveRequest
 * @version 1.0
 */
class PostAdminHostRemoveRequest {
    /**
     * Constructs a new <code>PostAdminHostRemoveRequest</code>.
     * @alias module:model/PostAdminHostRemoveRequest
     * @param hostId {String} 
     */
    constructor(hostId) { 
        
        PostAdminHostRemoveRequest.initialize(this, hostId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hostId) { 
        obj['hostId'] = hostId;
    }

    /**
     * Constructs a <code>PostAdminHostRemoveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminHostRemoveRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminHostRemoveRequest} The populated <code>PostAdminHostRemoveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminHostRemoveRequest();

            if (data.hasOwnProperty('hostId')) {
                obj['hostId'] = ApiClient.convertToType(data['hostId'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} hostId
 */
PostAdminHostRemoveRequest.prototype['hostId'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostAdminHostRemoveRequest.prototype['header'] = undefined;






export default PostAdminHostRemoveRequest;

