/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostUserPasswordChangeRequest model module.
 * @module model/PostUserPasswordChangeRequest
 * @version 1.0
 */
class PostUserPasswordChangeRequest {
    /**
     * Constructs a new <code>PostUserPasswordChangeRequest</code>.
     * @alias module:model/PostUserPasswordChangeRequest
     */
    constructor() { 
        
        PostUserPasswordChangeRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUserPasswordChangeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserPasswordChangeRequest} obj Optional instance to populate.
     * @return {module:model/PostUserPasswordChangeRequest} The populated <code>PostUserPasswordChangeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserPasswordChangeRequest();

            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
            if (data.hasOwnProperty('oldPassword')) {
                obj['oldPassword'] = ApiClient.convertToType(data['oldPassword'], 'String');
            }
            if (data.hasOwnProperty('newPassword')) {
                obj['newPassword'] = ApiClient.convertToType(data['newPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Header} header
 */
PostUserPasswordChangeRequest.prototype['header'] = undefined;

/**
 * User's old password encrypted with session key
 * @member {String} oldPassword
 */
PostUserPasswordChangeRequest.prototype['oldPassword'] = undefined;

/**
 * User's new password encrypted with session key
 * @member {String} newPassword
 */
PostUserPasswordChangeRequest.prototype['newPassword'] = undefined;






export default PostUserPasswordChangeRequest;

