/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';
import UserGroup from './UserGroup';

/**
 * The PostAdminUsergroupAddRequest model module.
 * @module model/PostAdminUsergroupAddRequest
 * @version 1.0
 */
class PostAdminUsergroupAddRequest {
    /**
     * Constructs a new <code>PostAdminUsergroupAddRequest</code>.
     * @alias module:model/PostAdminUsergroupAddRequest
     */
    constructor() { 
        
        PostAdminUsergroupAddRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminUsergroupAddRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminUsergroupAddRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminUsergroupAddRequest} The populated <code>PostAdminUsergroupAddRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminUsergroupAddRequest();

            if (data.hasOwnProperty('group')) {
                obj['group'] = UserGroup.constructFromObject(data['group']);
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserGroup} group
 */
PostAdminUsergroupAddRequest.prototype['group'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostAdminUsergroupAddRequest.prototype['header'] = undefined;






export default PostAdminUsergroupAddRequest;

