/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostAdminSysteminformationResponseEnabledFeatures from './PostAdminSysteminformationResponseEnabledFeatures';
import PostAdminSysteminformationResponseIpConfiguration from './PostAdminSysteminformationResponseIpConfiguration';

/**
 * The PostAdminSysteminformationResponse model module.
 * @module model/PostAdminSysteminformationResponse
 * @version 1.0
 */
class PostAdminSysteminformationResponse {
    /**
     * Constructs a new <code>PostAdminSysteminformationResponse</code>.
     * @alias module:model/PostAdminSysteminformationResponse
     */
    constructor() { 
        
        PostAdminSysteminformationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminSysteminformationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminSysteminformationResponse} obj Optional instance to populate.
     * @return {module:model/PostAdminSysteminformationResponse} The populated <code>PostAdminSysteminformationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminSysteminformationResponse();

            if (data.hasOwnProperty('operatingSystem')) {
                obj['operatingSystem'] = ApiClient.convertToType(data['operatingSystem'], 'String');
            }
            if (data.hasOwnProperty('processorInformation')) {
                obj['processorInformation'] = ApiClient.convertToType(data['processorInformation'], 'String');
            }
            if (data.hasOwnProperty('timeOnSystem')) {
                obj['timeOnSystem'] = ApiClient.convertToType(data['timeOnSystem'], 'String');
            }
            if (data.hasOwnProperty('systemUptime')) {
                obj['systemUptime'] = ApiClient.convertToType(data['systemUptime'], 'String');
            }
            if (data.hasOwnProperty('forgivaVersion')) {
                obj['forgivaVersion'] = ApiClient.convertToType(data['forgivaVersion'], 'String');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('ipConfiguration')) {
                obj['ipConfiguration'] = ApiClient.convertToType(data['ipConfiguration'], [PostAdminSysteminformationResponseIpConfiguration]);
            }
            if (data.hasOwnProperty('javaEnvironment')) {
                obj['javaEnvironment'] = ApiClient.convertToType(data['javaEnvironment'], 'String');
            }
            if (data.hasOwnProperty('enabledFeatures')) {
                obj['enabledFeatures'] = PostAdminSysteminformationResponseEnabledFeatures.constructFromObject(data['enabledFeatures']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} operatingSystem
 */
PostAdminSysteminformationResponse.prototype['operatingSystem'] = undefined;

/**
 * @member {String} processorInformation
 */
PostAdminSysteminformationResponse.prototype['processorInformation'] = undefined;

/**
 * @member {String} timeOnSystem
 */
PostAdminSysteminformationResponse.prototype['timeOnSystem'] = undefined;

/**
 * @member {String} systemUptime
 */
PostAdminSysteminformationResponse.prototype['systemUptime'] = undefined;

/**
 * @member {String} forgivaVersion
 */
PostAdminSysteminformationResponse.prototype['forgivaVersion'] = undefined;

/**
 * @member {String} hostname
 */
PostAdminSysteminformationResponse.prototype['hostname'] = undefined;

/**
 * @member {Array.<module:model/PostAdminSysteminformationResponseIpConfiguration>} ipConfiguration
 */
PostAdminSysteminformationResponse.prototype['ipConfiguration'] = undefined;

/**
 * @member {String} javaEnvironment
 */
PostAdminSysteminformationResponse.prototype['javaEnvironment'] = undefined;

/**
 * @member {module:model/PostAdminSysteminformationResponseEnabledFeatures} enabledFeatures
 */
PostAdminSysteminformationResponse.prototype['enabledFeatures'] = undefined;






export default PostAdminSysteminformationResponse;

