/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LogonState from './LogonState';

/**
 * The PostLoginResponse model module.
 * @module model/PostLoginResponse
 * @version 1.0
 */
class PostLoginResponse {
    /**
     * Constructs a new <code>PostLoginResponse</code>.
     * @alias module:model/PostLoginResponse
     */
    constructor() { 
        
        PostLoginResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostLoginResponse} obj Optional instance to populate.
     * @return {module:model/PostLoginResponse} The populated <code>PostLoginResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostLoginResponse();

            if (data.hasOwnProperty('logonState')) {
                obj['logonState'] = LogonState.constructFromObject(data['logonState']);
            }
            if (data.hasOwnProperty('twoFARequired')) {
                obj['twoFARequired'] = ApiClient.convertToType(data['twoFARequired'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/LogonState} logonState
 */
PostLoginResponse.prototype['logonState'] = undefined;

/**
 * 2FA service is required or not.
 * @member {Boolean} twoFARequired
 */
PostLoginResponse.prototype['twoFARequired'] = undefined;






export default PostLoginResponse;

