/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The PostAdminUserByusergroupResponse model module.
 * @module model/PostAdminUserByusergroupResponse
 * @version 1.0
 */
class PostAdminUserByusergroupResponse {
    /**
     * Constructs a new <code>PostAdminUserByusergroupResponse</code>.
     * @alias module:model/PostAdminUserByusergroupResponse
     */
    constructor() { 
        
        PostAdminUserByusergroupResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminUserByusergroupResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminUserByusergroupResponse} obj Optional instance to populate.
     * @return {module:model/PostAdminUserByusergroupResponse} The populated <code>PostAdminUserByusergroupResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminUserByusergroupResponse();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [User]);
            }
            if (data.hasOwnProperty('totalUserCount')) {
                obj['totalUserCount'] = ApiClient.convertToType(data['totalUserCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/User>} users
 */
PostAdminUserByusergroupResponse.prototype['users'] = undefined;

/**
 * Total number of users within specific group
 * @member {Number} totalUserCount
 */
PostAdminUserByusergroupResponse.prototype['totalUserCount'] = undefined;






export default PostAdminUserByusergroupResponse;

