/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostUserMetadataHostResponseHosts model module.
 * @module model/PostUserMetadataHostResponseHosts
 * @version 1.0
 */
class PostUserMetadataHostResponseHosts {
    /**
     * Constructs a new <code>PostUserMetadataHostResponseHosts</code>.
     * @alias module:model/PostUserMetadataHostResponseHosts
     */
    constructor() { 
        
        PostUserMetadataHostResponseHosts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUserMetadataHostResponseHosts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserMetadataHostResponseHosts} obj Optional instance to populate.
     * @return {module:model/PostUserMetadataHostResponseHosts} The populated <code>PostUserMetadataHostResponseHosts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserMetadataHostResponseHosts();

            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} host
 */
PostUserMetadataHostResponseHosts.prototype['host'] = undefined;






export default PostUserMetadataHostResponseHosts;

