/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';

/**
 * The PostUserMetadataHostRequest model module.
 * @module model/PostUserMetadataHostRequest
 * @version 1.0
 */
class PostUserMetadataHostRequest {
    /**
     * Constructs a new <code>PostUserMetadataHostRequest</code>.
     * @alias module:model/PostUserMetadataHostRequest
     */
    constructor() { 
        
        PostUserMetadataHostRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUserMetadataHostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserMetadataHostRequest} obj Optional instance to populate.
     * @return {module:model/PostUserMetadataHostRequest} The populated <code>PostUserMetadataHostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserMetadataHostRequest();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], 'String');
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} filter
 */
PostUserMetadataHostRequest.prototype['filter'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostUserMetadataHostRequest.prototype['header'] = undefined;






export default PostUserMetadataHostRequest;

