/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Metadata from './Metadata';

/**
 * The PostUserMetadataSearchResponse model module.
 * @module model/PostUserMetadataSearchResponse
 * @version 1.0
 */
class PostUserMetadataSearchResponse {
    /**
     * Constructs a new <code>PostUserMetadataSearchResponse</code>.
     * @alias module:model/PostUserMetadataSearchResponse
     */
    constructor() { 
        
        PostUserMetadataSearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostUserMetadataSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostUserMetadataSearchResponse} obj Optional instance to populate.
     * @return {module:model/PostUserMetadataSearchResponse} The populated <code>PostUserMetadataSearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostUserMetadataSearchResponse();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], [Metadata]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Metadata>} metadata
 */
PostUserMetadataSearchResponse.prototype['metadata'] = undefined;






export default PostUserMetadataSearchResponse;

