/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It can be used by any 3rd party clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Header from './Header';
import UserGroup from './UserGroup';

/**
 * The PostAdminUsergroupUpdateRequest model module.
 * @module model/PostAdminUsergroupUpdateRequest
 * @version 1.0
 */
class PostAdminUsergroupUpdateRequest {
    /**
     * Constructs a new <code>PostAdminUsergroupUpdateRequest</code>.
     * @alias module:model/PostAdminUsergroupUpdateRequest
     */
    constructor() { 
        
        PostAdminUsergroupUpdateRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostAdminUsergroupUpdateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostAdminUsergroupUpdateRequest} obj Optional instance to populate.
     * @return {module:model/PostAdminUsergroupUpdateRequest} The populated <code>PostAdminUsergroupUpdateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostAdminUsergroupUpdateRequest();

            if (data.hasOwnProperty('userGroup')) {
                obj['userGroup'] = UserGroup.constructFromObject(data['userGroup']);
            }
            if (data.hasOwnProperty('header')) {
                obj['header'] = Header.constructFromObject(data['header']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/UserGroup} userGroup
 */
PostAdminUsergroupUpdateRequest.prototype['userGroup'] = undefined;

/**
 * @member {module:model/Header} header
 */
PostAdminUsergroupUpdateRequest.prototype['header'] = undefined;






export default PostAdminUsergroupUpdateRequest;

