/**
 * IntegratorAPI
 * Forgiva Integrator API containing whole operations between Forgiva SuperClient and Integrator server traffic. It  can be used by any 3rd party clients. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: root@sceptive.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Application from './model/Application';
import Header from './model/Header';
import Host from './model/Host';
import LogonState from './model/LogonState';
import Metadata from './model/Metadata';
import MetadataGroup from './model/MetadataGroup';
import OperationResult from './model/OperationResult';
import PostAdminApplicationAddRequest from './model/PostAdminApplicationAddRequest';
import PostAdminApplicationRemoveRequest from './model/PostAdminApplicationRemoveRequest';
import PostAdminApplicationUpdateRequest from './model/PostAdminApplicationUpdateRequest';
import PostAdminApplicationsRequest from './model/PostAdminApplicationsRequest';
import PostAdminApplicationsResponse from './model/PostAdminApplicationsResponse';
import PostAdminHostAddRequest from './model/PostAdminHostAddRequest';
import PostAdminHostRemoveRequest from './model/PostAdminHostRemoveRequest';
import PostAdminHostUpdateRequest from './model/PostAdminHostUpdateRequest';
import PostAdminHostsRequest from './model/PostAdminHostsRequest';
import PostAdminHostsResponse from './model/PostAdminHostsResponse';
import PostAdminReportsRequest from './model/PostAdminReportsRequest';
import PostAdminReportsResponse from './model/PostAdminReportsResponse';
import PostAdminResourceusageRequest from './model/PostAdminResourceusageRequest';
import PostAdminResourceusageResponse from './model/PostAdminResourceusageResponse';
import PostAdminResourceusageResponseCpuUsageByDay from './model/PostAdminResourceusageResponseCpuUsageByDay';
import PostAdminResourceusageResponseCpuUsageByHour from './model/PostAdminResourceusageResponseCpuUsageByHour';
import PostAdminSysteminformationRequest from './model/PostAdminSysteminformationRequest';
import PostAdminSysteminformationResponse from './model/PostAdminSysteminformationResponse';
import PostAdminSysteminformationResponseEnabledFeatures from './model/PostAdminSysteminformationResponseEnabledFeatures';
import PostAdminSysteminformationResponseIpConfiguration from './model/PostAdminSysteminformationResponseIpConfiguration';
import PostAdminUserAddRequest from './model/PostAdminUserAddRequest';
import PostAdminUserByusergroupRequest from './model/PostAdminUserByusergroupRequest';
import PostAdminUserByusergroupResponse from './model/PostAdminUserByusergroupResponse';
import PostAdminUserRemoveRequest from './model/PostAdminUserRemoveRequest';
import PostAdminUserUpdateRequest from './model/PostAdminUserUpdateRequest';
import PostAdminUsergroupAddRequest from './model/PostAdminUsergroupAddRequest';
import PostAdminUsergroupRemoveRequest from './model/PostAdminUsergroupRemoveRequest';
import PostAdminUsergroupUpdateRequest from './model/PostAdminUsergroupUpdateRequest';
import PostAdminUsergroupsRequest from './model/PostAdminUsergroupsRequest';
import PostAdminUsergroupsResponse from './model/PostAdminUsergroupsResponse';
import PostLogin2faRequest from './model/PostLogin2faRequest';
import PostLogin2faResponse from './model/PostLogin2faResponse';
import PostLoginRequest from './model/PostLoginRequest';
import PostLoginResponse from './model/PostLoginResponse';
import PostLogoutRequest from './model/PostLogoutRequest';
import PostNewSessionRequest from './model/PostNewSessionRequest';
import PostNewSessionResponse from './model/PostNewSessionResponse';
import PostUser2faDisableRequest from './model/PostUser2faDisableRequest';
import PostUser2faEnableRequest from './model/PostUser2faEnableRequest';
import PostUserBackupExportRequest from './model/PostUserBackupExportRequest';
import PostUserBackupImportRequest from './model/PostUserBackupImportRequest';
import PostUserGenerateRequest from './model/PostUserGenerateRequest';
import PostUserGenerateResponse from './model/PostUserGenerateResponse';
import PostUserMetadataAddRequest from './model/PostUserMetadataAddRequest';
import PostUserMetadataBygroupRequest from './model/PostUserMetadataBygroupRequest';
import PostUserMetadataBygroupResponse from './model/PostUserMetadataBygroupResponse';
import PostUserMetadataGroupAddRequest from './model/PostUserMetadataGroupAddRequest';
import PostUserMetadataGroupRemoveRequest from './model/PostUserMetadataGroupRemoveRequest';
import PostUserMetadataGroupsRequest from './model/PostUserMetadataGroupsRequest';
import PostUserMetadataGroupsResponse from './model/PostUserMetadataGroupsResponse';
import PostUserMetadataHostRequest from './model/PostUserMetadataHostRequest';
import PostUserMetadataHostResponse from './model/PostUserMetadataHostResponse';
import PostUserMetadataHostResponseHosts from './model/PostUserMetadataHostResponseHosts';
import PostUserMetadataRemoveRequest from './model/PostUserMetadataRemoveRequest';
import PostUserMetadataSearchRequest from './model/PostUserMetadataSearchRequest';
import PostUserMetadataSearchResponse from './model/PostUserMetadataSearchResponse';
import PostUserPasswordChangeRequest from './model/PostUserPasswordChangeRequest';
import PostUserSettingsGetRequest from './model/PostUserSettingsGetRequest';
import PostUserSettingsGetResponse from './model/PostUserSettingsGetResponse';
import PostUserSettingsSetRequest from './model/PostUserSettingsSetRequest';
import Report from './model/Report';
import User from './model/User';
import UserGroup from './model/UserGroup';
import AdministratorOperationsApi from './api/AdministratorOperationsApi';
import DefaultApi from './api/DefaultApi';
import UserOperationsApi from './api/UserOperationsApi';


/**
* Forgiva_Integrator_API_containing_whole_operations_between_Forgiva_SuperClient_and_Integrator_server_traffic__It_can_be_used_by_any_3rd_party_clients_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var IntegratorApi = require('index'); // See note below*.
* var xxxSvc = new IntegratorApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new IntegratorApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new IntegratorApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new IntegratorApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Application model constructor.
     * @property {module:model/Application}
     */
    Application,

    /**
     * The Header model constructor.
     * @property {module:model/Header}
     */
    Header,

    /**
     * The Host model constructor.
     * @property {module:model/Host}
     */
    Host,

    /**
     * The LogonState model constructor.
     * @property {module:model/LogonState}
     */
    LogonState,

    /**
     * The Metadata model constructor.
     * @property {module:model/Metadata}
     */
    Metadata,

    /**
     * The MetadataGroup model constructor.
     * @property {module:model/MetadataGroup}
     */
    MetadataGroup,

    /**
     * The OperationResult model constructor.
     * @property {module:model/OperationResult}
     */
    OperationResult,

    /**
     * The PostAdminApplicationAddRequest model constructor.
     * @property {module:model/PostAdminApplicationAddRequest}
     */
    PostAdminApplicationAddRequest,

    /**
     * The PostAdminApplicationRemoveRequest model constructor.
     * @property {module:model/PostAdminApplicationRemoveRequest}
     */
    PostAdminApplicationRemoveRequest,

    /**
     * The PostAdminApplicationUpdateRequest model constructor.
     * @property {module:model/PostAdminApplicationUpdateRequest}
     */
    PostAdminApplicationUpdateRequest,

    /**
     * The PostAdminApplicationsRequest model constructor.
     * @property {module:model/PostAdminApplicationsRequest}
     */
    PostAdminApplicationsRequest,

    /**
     * The PostAdminApplicationsResponse model constructor.
     * @property {module:model/PostAdminApplicationsResponse}
     */
    PostAdminApplicationsResponse,

    /**
     * The PostAdminHostAddRequest model constructor.
     * @property {module:model/PostAdminHostAddRequest}
     */
    PostAdminHostAddRequest,

    /**
     * The PostAdminHostRemoveRequest model constructor.
     * @property {module:model/PostAdminHostRemoveRequest}
     */
    PostAdminHostRemoveRequest,

    /**
     * The PostAdminHostUpdateRequest model constructor.
     * @property {module:model/PostAdminHostUpdateRequest}
     */
    PostAdminHostUpdateRequest,

    /**
     * The PostAdminHostsRequest model constructor.
     * @property {module:model/PostAdminHostsRequest}
     */
    PostAdminHostsRequest,

    /**
     * The PostAdminHostsResponse model constructor.
     * @property {module:model/PostAdminHostsResponse}
     */
    PostAdminHostsResponse,

    /**
     * The PostAdminReportsRequest model constructor.
     * @property {module:model/PostAdminReportsRequest}
     */
    PostAdminReportsRequest,

    /**
     * The PostAdminReportsResponse model constructor.
     * @property {module:model/PostAdminReportsResponse}
     */
    PostAdminReportsResponse,

    /**
     * The PostAdminResourceusageRequest model constructor.
     * @property {module:model/PostAdminResourceusageRequest}
     */
    PostAdminResourceusageRequest,

    /**
     * The PostAdminResourceusageResponse model constructor.
     * @property {module:model/PostAdminResourceusageResponse}
     */
    PostAdminResourceusageResponse,

    /**
     * The PostAdminResourceusageResponseCpuUsageByDay model constructor.
     * @property {module:model/PostAdminResourceusageResponseCpuUsageByDay}
     */
    PostAdminResourceusageResponseCpuUsageByDay,

    /**
     * The PostAdminResourceusageResponseCpuUsageByHour model constructor.
     * @property {module:model/PostAdminResourceusageResponseCpuUsageByHour}
     */
    PostAdminResourceusageResponseCpuUsageByHour,

    /**
     * The PostAdminSysteminformationRequest model constructor.
     * @property {module:model/PostAdminSysteminformationRequest}
     */
    PostAdminSysteminformationRequest,

    /**
     * The PostAdminSysteminformationResponse model constructor.
     * @property {module:model/PostAdminSysteminformationResponse}
     */
    PostAdminSysteminformationResponse,

    /**
     * The PostAdminSysteminformationResponseEnabledFeatures model constructor.
     * @property {module:model/PostAdminSysteminformationResponseEnabledFeatures}
     */
    PostAdminSysteminformationResponseEnabledFeatures,

    /**
     * The PostAdminSysteminformationResponseIpConfiguration model constructor.
     * @property {module:model/PostAdminSysteminformationResponseIpConfiguration}
     */
    PostAdminSysteminformationResponseIpConfiguration,

    /**
     * The PostAdminUserAddRequest model constructor.
     * @property {module:model/PostAdminUserAddRequest}
     */
    PostAdminUserAddRequest,

    /**
     * The PostAdminUserByusergroupRequest model constructor.
     * @property {module:model/PostAdminUserByusergroupRequest}
     */
    PostAdminUserByusergroupRequest,

    /**
     * The PostAdminUserByusergroupResponse model constructor.
     * @property {module:model/PostAdminUserByusergroupResponse}
     */
    PostAdminUserByusergroupResponse,

    /**
     * The PostAdminUserRemoveRequest model constructor.
     * @property {module:model/PostAdminUserRemoveRequest}
     */
    PostAdminUserRemoveRequest,

    /**
     * The PostAdminUserUpdateRequest model constructor.
     * @property {module:model/PostAdminUserUpdateRequest}
     */
    PostAdminUserUpdateRequest,

    /**
     * The PostAdminUsergroupAddRequest model constructor.
     * @property {module:model/PostAdminUsergroupAddRequest}
     */
    PostAdminUsergroupAddRequest,

    /**
     * The PostAdminUsergroupRemoveRequest model constructor.
     * @property {module:model/PostAdminUsergroupRemoveRequest}
     */
    PostAdminUsergroupRemoveRequest,

    /**
     * The PostAdminUsergroupUpdateRequest model constructor.
     * @property {module:model/PostAdminUsergroupUpdateRequest}
     */
    PostAdminUsergroupUpdateRequest,

    /**
     * The PostAdminUsergroupsRequest model constructor.
     * @property {module:model/PostAdminUsergroupsRequest}
     */
    PostAdminUsergroupsRequest,

    /**
     * The PostAdminUsergroupsResponse model constructor.
     * @property {module:model/PostAdminUsergroupsResponse}
     */
    PostAdminUsergroupsResponse,

    /**
     * The PostLogin2faRequest model constructor.
     * @property {module:model/PostLogin2faRequest}
     */
    PostLogin2faRequest,

    /**
     * The PostLogin2faResponse model constructor.
     * @property {module:model/PostLogin2faResponse}
     */
    PostLogin2faResponse,

    /**
     * The PostLoginRequest model constructor.
     * @property {module:model/PostLoginRequest}
     */
    PostLoginRequest,

    /**
     * The PostLoginResponse model constructor.
     * @property {module:model/PostLoginResponse}
     */
    PostLoginResponse,

    /**
     * The PostLogoutRequest model constructor.
     * @property {module:model/PostLogoutRequest}
     */
    PostLogoutRequest,

    /**
     * The PostNewSessionRequest model constructor.
     * @property {module:model/PostNewSessionRequest}
     */
    PostNewSessionRequest,

    /**
     * The PostNewSessionResponse model constructor.
     * @property {module:model/PostNewSessionResponse}
     */
    PostNewSessionResponse,

    /**
     * The PostUser2faDisableRequest model constructor.
     * @property {module:model/PostUser2faDisableRequest}
     */
    PostUser2faDisableRequest,

    /**
     * The PostUser2faEnableRequest model constructor.
     * @property {module:model/PostUser2faEnableRequest}
     */
    PostUser2faEnableRequest,

    /**
     * The PostUserBackupExportRequest model constructor.
     * @property {module:model/PostUserBackupExportRequest}
     */
    PostUserBackupExportRequest,

    /**
     * The PostUserBackupImportRequest model constructor.
     * @property {module:model/PostUserBackupImportRequest}
     */
    PostUserBackupImportRequest,

    /**
     * The PostUserGenerateRequest model constructor.
     * @property {module:model/PostUserGenerateRequest}
     */
    PostUserGenerateRequest,

    /**
     * The PostUserGenerateResponse model constructor.
     * @property {module:model/PostUserGenerateResponse}
     */
    PostUserGenerateResponse,

    /**
     * The PostUserMetadataAddRequest model constructor.
     * @property {module:model/PostUserMetadataAddRequest}
     */
    PostUserMetadataAddRequest,

    /**
     * The PostUserMetadataBygroupRequest model constructor.
     * @property {module:model/PostUserMetadataBygroupRequest}
     */
    PostUserMetadataBygroupRequest,

    /**
     * The PostUserMetadataBygroupResponse model constructor.
     * @property {module:model/PostUserMetadataBygroupResponse}
     */
    PostUserMetadataBygroupResponse,

    /**
     * The PostUserMetadataGroupAddRequest model constructor.
     * @property {module:model/PostUserMetadataGroupAddRequest}
     */
    PostUserMetadataGroupAddRequest,

    /**
     * The PostUserMetadataGroupRemoveRequest model constructor.
     * @property {module:model/PostUserMetadataGroupRemoveRequest}
     */
    PostUserMetadataGroupRemoveRequest,

    /**
     * The PostUserMetadataGroupsRequest model constructor.
     * @property {module:model/PostUserMetadataGroupsRequest}
     */
    PostUserMetadataGroupsRequest,

    /**
     * The PostUserMetadataGroupsResponse model constructor.
     * @property {module:model/PostUserMetadataGroupsResponse}
     */
    PostUserMetadataGroupsResponse,

    /**
     * The PostUserMetadataHostRequest model constructor.
     * @property {module:model/PostUserMetadataHostRequest}
     */
    PostUserMetadataHostRequest,

    /**
     * The PostUserMetadataHostResponse model constructor.
     * @property {module:model/PostUserMetadataHostResponse}
     */
    PostUserMetadataHostResponse,

    /**
     * The PostUserMetadataHostResponseHosts model constructor.
     * @property {module:model/PostUserMetadataHostResponseHosts}
     */
    PostUserMetadataHostResponseHosts,

    /**
     * The PostUserMetadataRemoveRequest model constructor.
     * @property {module:model/PostUserMetadataRemoveRequest}
     */
    PostUserMetadataRemoveRequest,

    /**
     * The PostUserMetadataSearchRequest model constructor.
     * @property {module:model/PostUserMetadataSearchRequest}
     */
    PostUserMetadataSearchRequest,

    /**
     * The PostUserMetadataSearchResponse model constructor.
     * @property {module:model/PostUserMetadataSearchResponse}
     */
    PostUserMetadataSearchResponse,

    /**
     * The PostUserPasswordChangeRequest model constructor.
     * @property {module:model/PostUserPasswordChangeRequest}
     */
    PostUserPasswordChangeRequest,

    /**
     * The PostUserSettingsGetRequest model constructor.
     * @property {module:model/PostUserSettingsGetRequest}
     */
    PostUserSettingsGetRequest,

    /**
     * The PostUserSettingsGetResponse model constructor.
     * @property {module:model/PostUserSettingsGetResponse}
     */
    PostUserSettingsGetResponse,

    /**
     * The PostUserSettingsSetRequest model constructor.
     * @property {module:model/PostUserSettingsSetRequest}
     */
    PostUserSettingsSetRequest,

    /**
     * The Report model constructor.
     * @property {module:model/Report}
     */
    Report,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserGroup model constructor.
     * @property {module:model/UserGroup}
     */
    UserGroup,

    /**
    * The AdministratorOperationsApi service constructor.
    * @property {module:api/AdministratorOperationsApi}
    */
    AdministratorOperationsApi,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi,

    /**
    * The UserOperationsApi service constructor.
    * @property {module:api/UserOperationsApi}
    */
    UserOperationsApi
};
